name: 'Close stale PRs'
on:
  schedule:
    - cron: '0 16 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/stale@v10
        with:
          stale-pr-message: 'This PR is stale because it has been open 3 days with no activity. Remove stale label or comment or this will be closed in 1 day.'
          close-pr-message: 'This PR was closed because it has been stalled for 4 days with no activity.'
          days-before-stale: 3
          days-before-close: 4
          days-before-issue-stale: -1
          days-before-issue-close: -1
